export const REFERENCES = [
  {
    slug: 'samedos',
    title: 'Samedos',
    subtitle: 'Arbeitsmedizinische Praxis',
    url: 'https://www.samedos.de',
    preview: '/referenzen/samedoswebsite.webp',
    tags: ['Astro', 'Tailwind', 'Sanity', 'Vercel'],
    category: 'Medizin',
  },
  {
    slug: 'er-und-sie',
    title: 'Er & Sie',
    subtitle: 'Eckkneipe in Bremen Walle',
    url: 'https://erundsiebremen.de',
    preview: '/referenzen/erundsiewebsite.webp',
    tags: ['Astro', 'Tailwind', 'Sanity', 'Vercel'],
    category: 'Gastronomie',
  },
  {
    slug: 'waermepower',
    title: 'Wärmepower',
    subtitle: 'Heizung, Wärmepumpe, Sanitär',
    url: 'https://waermepower.de',
    preview: '/referenzen/waermepowerwebsite.webp',
    tags: ['Astro', 'Tailwind', 'Sanity', 'Vercel'],
    category: 'Handwerk',
  },
  {
    slug: 'ibi-doc',
    title: 'Institut für Betriebsmedizin Isernhagen',
    shortTitle: 'Institut Betriebsmedizin Isernhagen',
    subtitle: 'Betriebsmedizinische Praxis',
    url: 'https://www.ibi-doc.de',
    preview: '/referenzen/ibi-doc-website.webp',
    tags: ['Astro', 'Tailwind', 'Sanity', 'Vercel'],
    category: 'Medizin',
  },
  {
    slug: 'kirsch-dach-fassade',
    title: 'Kirsch Dach & Fassade',
    subtitle: 'Dach & Fassade in Bremen',
    url: 'https://kirsch-dach-fassade.de',
    preview: '/referenzen/kirsch-dach-fassade.webp',
    tags: ['Astro', 'Tailwind', 'Sanity', 'Vercel'],
    category: 'Handwerk',
  },
] as const;
